name: YouTube M3U Güncelleme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository'yi indir
      uses: actions/checkout@v4
      
    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Gerekli kütüphaneleri yükle
      run: |
        pip install requests
        
    - name: YouTube M3U scriptini çalıştır
      run: python youtube_m3u_generator.py
      
    - name: Debug dosyasını kontrol et
      run: |
        if [ -f debug_html.txt ]; then
          echo "=== DEBUG HTML İÇERİĞİ ==="
          head -n 10 debug_html.txt
        else
          echo "Debug dosyası oluşturulmamış"
        fi
      
    - name: M3U dosyasını kontrol et
      run: |
        if [ -f youtube.m3u ]; then
          echo "=== M3U İÇERİĞİ ==="
          cat youtube.m3u
        else
          echo "M3U dosyası oluşturulmamış"
        fi
      
    - name: Değişiklikleri kaydet ve gönder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add youtube.m3u
        git diff --staged --quiet || git commit -m "YouTube M3U güncellendi - $(date +'%Y-%m-%d %H:%M')"
        git push
